### ISSUE TITLE
Tables are uncraftable and don't spawn in the world

### ISSUE THREAD

**Issue by Robbie-Poidevin** [frikinjay/morevillagers#2]
Title says it all. This mod doesn't work because there is no way to get the tables in survival

**Comment by frikinjay** [comment]
What loader are you on?

**Comment by spzt101** [comment]
Having this issue too. Fabric 1.21.1.

**Comment by SkyRunner55** [comment]
i can't tell if the craft works in the latest version since[ the mod dosn't load](https://github.com/frikinjay/morevillagers/issues/4), and [i'm not the only one having this issue](https://github.com/frikinjay/morevillagers/issues/3)

**Comment by frikinjay** [comment]
Fixed in 5.0.3

**Comment by SkyRunner55** [comment]
for those that still have the issue, delete the old "morevillagers-common" in the config, the new one will fix the problem
