### ISSUE TITLE
Not a valid mod in Neoforge 1.21.1

### ISSUE THREAD

**Issue by danmvision** [frikinjay/morevillagers#3]
https://i.imgur.com/mjTBWLe.png

**Comment by Temil2006** [comment]
same issue here sense going up to 5.0.2 .. rolled back to 5.0.1 and loads fine.

**Comment by SkyRunner55** [comment]
[Same here](https://github.com/frikinjay/morevillagers/issues/4)

**Comment by frikinjay** [comment]
Fixed in 5.0.3
