### ISSUE TITLE
Neoforge - The mod don't load 

### ISSUE THREAD

**Issue by SkyRunner55** [frikinjay/morevillagers#4]
in the mod version 5.0.2, the mod will be ignored and won't work when starting the game with error message
i created a new cursedforge profile with only this mod 

![image](https://github.com/user-attachments/assets/c86d0c03-59ff-4dae-a8d9-615d85c735d1)

[latest.log](https://github.com/user-attachments/files/18005568/latest.log)

**Comment by SHXRKIEgg** [comment]
Same

**Comment by frikinjay** [comment]
Fixed in 5.0.3
