### ISSUE TITLE
not valid mod for neo

### ISSUE THREAD

**Issue by VaporeonScripts** [frikinjay/morevillagers#5]
![image](https://github.com/user-attachments/assets/8d8bd1e6-b079-4c59-ab3f-548fdb9a065b)

**Comment by SkyRunner55** [comment]
yes the bug was reported already, but the modder doesn't seem active sadly, i hope this bug will be fix

https://github.com/frikinjay/morevillagers/issues/3
https://github.com/frikinjay/morevillagers/issues/4

**Comment by frikinjay** [comment]
Fixed in 5.0.3

**Comment by SkyRunner55** [comment]
> Fixed in 5.0.3

perfect, thx  :)
